# Generated by Django 4.1.1 on 2022-10-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioSistema', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=30)),
                ('confirmarSenha', models.CharField(max_length=30)),
            ],
        ),
    ]
