# Generated by Django 4.1.2 on 2022-10-24 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troca',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usuario'),
        ),
    ]
